"""Shared utilities for building OME-Zarr image converters."""

from importlib.metadata import version

from ome_zarr_converters_tools.core import (
    AttributeType,
    Tile,
    TiledImage,
)
from ome_zarr_converters_tools.fractal import (
    AcquisitionOptions,
    ChannelInfoUI,
    ConvertParallelInitArgs,
    ImageListUpdateDict,
    MultiprocessingRunner,
    RunnerType,
    SequentialRunner,
    ThreadedRunner,
    converters_tools_models,
    exec_compound_task,
    generic_compute_task,
    setup_images_for_conversion,
)
from ome_zarr_converters_tools.models import (
    AcquisitionDetails,
    ChannelInfo,
    ChunkingStrategy,
    CollectionInterface,
    CollectionInterfaceType,
    ConverterOptions,
    DaskScheduler,
    DataTypeEnum,
    DefaultImageLoader,
    DefaultScheduler,
    FixedSizeChunking,
    FovBasedChunking,
    ImageInPlate,
    ImageLoaderInterfaceType,
    OmeZarrOptions,
    OverwriteMode,
    ProcessScheduler,
    RuntimeSettings,
    SingleImage,
    StageOrientation,
    SynchronousScheduler,
    ThreadScheduler,
    basename_url,
    default_axes_builder,
    filesystem_for_url,
    glob_url_paths,
    is_absolute_url,
    join_url_paths,
    parent_url,
)
from ome_zarr_converters_tools.pipelines import (
    tiles_aggregation_pipeline,
)

__version__ = version("ome-zarr-converters-tools")
__author__ = "Lorenzo Cerrone"
__email__ = "lorenzo.cerrone@uzh.ch"

__all__ = [
    "AcquisitionDetails",
    "AcquisitionOptions",
    "AttributeType",
    "ChannelInfo",
    "ChannelInfoUI",
    "ChunkingStrategy",
    "CollectionInterface",
    "CollectionInterfaceType",
    "ConvertParallelInitArgs",
    "ConverterOptions",
    "DaskScheduler",
    "DataTypeEnum",
    "DefaultImageLoader",
    "DefaultScheduler",
    "FixedSizeChunking",
    "FovBasedChunking",
    "ImageInPlate",
    "ImageListUpdateDict",
    "ImageLoaderInterfaceType",
    "MultiprocessingRunner",
    "OmeZarrOptions",
    "OverwriteMode",
    "ProcessScheduler",
    "RunnerType",
    "RuntimeSettings",
    "SequentialRunner",
    "SingleImage",
    "StageOrientation",
    "SynchronousScheduler",
    "ThreadScheduler",
    "ThreadedRunner",
    "Tile",
    "TiledImage",
    "basename_url",
    "converters_tools_models",
    "default_axes_builder",
    "exec_compound_task",
    "filesystem_for_url",
    "generic_compute_task",
    "glob_url_paths",
    "is_absolute_url",
    "join_url_paths",
    "parent_url",
    "setup_images_for_conversion",
    "tiles_aggregation_pipeline",
]
